version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  test_the_script: # this can be any name you choose
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run test
          name: tests
  
  push_to_github:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          command: echo "sup mofo"
          name: just a msg
      # - run
      #     command: git commit -m "random msg"
      #     name: commit
      # -run
      #     command: git push origin main
      #     name: push

workflows:
  test_my_app:
    jobs:
      - test_the_script
      - push_to_github:
          requires:
            - test_the_script

